<?php

$data = [
    '2020 - ' . date("Y") => [
        'mathbrain' => [
            'title' => 'Math Brain - Arithmetic Learning Games Quiz',
            'desc' => 'My own project. App to help you upgrade your math skills. Develop concentration, reaction, and speed of your brain by performing daily exercises. Achieve arithmetic abilities in basic operations - multiplication, division, subtraction, and addition.',
            'link' => 'https://apps.apple.com/app/apple-store/id1506953829?pt=121456226&ct=website_right&mt=8&platform=iphone',
            'img' => 'mathbrain'
        ],
        'twin' => [
            'title' => 'Twin - Pair Match Symbol Cards',
            'desc' => 'Twin - is a fun symbol matching game where you need to be more attentive and faster than your rivals.',
            'link' => 'https://apps.apple.com/us/app/twin-spot-it-match-challenge/id1520230707',
            'img' => 'twin'
        ],
        'wordix' => [
            'title' => 'Wordix – Memorize word Game',
            'desc' => 'My own project. Wordix - a unique app with which you will increase the concentration, reaction, and speed of your brain! You can develop memory, attention, and logical thinking. With every-day constant basic memorization exercises, you will also develop visual memory.',
            'link' => 'https://apps.apple.com/app/apple-store/id1536743626?&ct=landing&mt=8',
            'img' => 'wordix'
        ],
    ],
    '2019' => [
        'katalyst' => [
            'title' => 'Katalyst',
            'desc' => 'Katalyst POS & Cloud Operating System',
            'link' => 'https://apple.co/3aq0uJa',
            'img' => 'katalyst'
        ],
        'tarot' => [
            'title' => 'Tarot',
            'desc' => 'Tarot card reading & meanings - complete development from scratch to the AppStore, application with a complicated user interface design and goodly animations.',
            'link' => 'https://apps.apple.com/us/app/tarot-card-reading-meanings/id388124231#?platform=iphone',
            'img' => 'tarot'
        ],
    ],
    '2017 - 2018' => [
        'autorent' => [
            'title' => 'AUTO.rent',
            'desc' => 'AUTO.rent - app for private car rentals',
            'link' => 'http://apple.co/2AiNaH6',
            'img' => 'autorent'
        ],
        'tipntrip' => [
                'title' => 'tip n trip',
                'desc' => 'tip n trip - service for travelers notes',
                'link' => '',
                'img' => 'tipntrip'
            ],
        'solo' => [
            'title' => 'SOLO',
            'desc' => 'SOLO - international calling application',
            'link' => '',
            'img' => 'solo'
        ],
    ],
    '2016' => [
        'forwardhorse' => [
            'title' => 'FORWARDHORSE',
            'desc' => 'Development of iOS app "Forwardhorse". Mini game to bet on real exchange rates, visualized as running horses.',
            'link' => '',
            'img' => 'forwardhorse'
        ],
        'gasstationmap' => [
            'title' => 'GAS STATIONS MAP',
            'desc' => 'Development of iOS app "Gas stations map" to search for the nearest gas station, compare prices and read reviews',
            'link' => '',
            'img' => 'gasstationmap'
        ],
        'promed' => [
            'title' => 'PROMED',
            'desc' => 'Developing iOS applications for medical consultations and search medical organizations "ProMed"',
            'link' => '',
            'img' => 'promed'
        ],
        'starway' => [
            'title' => 'STARWAY',
            'desc' => 'iOS app "StarWay" for order the horoscopes',
            'link' => '',
            'img' => 'starway'
        ],
        'needaderm' => [
            'title' => 'NEED A DERM',
            'desc' => 'Development of iOS application for remote dermathologist consultations',
            'link' => '',
            'img' => 'needaderm'
        ],
    ],
    '2015' => [
        'readyforsky' => [
            'title' => 'READY FOR SKY',
            'desc' => 'Project for smart home management Ready For Sky (R4S). READYFORSKY.COM<br>Working in the team and support the development of new modules to the iOS application.<br>Coordination of work teams, the role of lead developer.<br>Architectural bug fixes and improvements, directed towards the scalability and enhancing the prestige of the project.<br>Experience of software development methodologies Agile/Scrum, GitFlow. Wiki-documentation.<br><br>the Work is done in the staff of OOO "Tekhnopoisk"/ OOO "Erlab" (REDMOND, Ready For Sky)',
            'link' => 'https://itunes.apple.com/ru/app/ready-for-sky-otkroj-novuu/id927991375?mt=8',
            'img' => 'readyforsky',
            'img2' => 'readyforsky2'
        ],
        'zonesdating' => [
            'title' => 'ZONES',
            'desc' => 'IOS application, games of Dating service Zones',
            'link' => '',
            'img' => 'zonesdating'
        ],
        'wantticket' => [
            'title' => 'WANT TICKET',
            'desc' => 'Develop iOS application for hand to hand selling tickets',
            'link' => '',
            'img' => 'wantticket'
        ],
        'socketsmap' => [
            'title' => 'SOCKETS MAP',
            'desc' => 'Develop iOS application for exploring sockets for charging mobile phone',
            'link' => '',
            'img' => 'socketsmap'
        ],
        'weightanalyze' => [
            'title' => 'WEIGHT ANALYZE',
            'desc' => 'A project created for self-development and learning new technologies.',
            'link' => '',
            'img' => 'weightanalyze'
        ],
    ],
    '2014' => [
        'ninetydays' => [
            'title' => 'NINETY DAYS',
            'desc' => 'Development of iOS of the application Ninety days.',
            'link' => '',
            'img' => 'ninetydays'
        ],
        'vmeste' => [
            'title' => 'VMESTE',
            'desc' => 'Develop iOS Dating app Vmeste (Together)<br>the<br><br>1. App picks up people that may be of interest to you;<br>2. using the app you can tag any people. Selected users will see your profile with equal sympathy<br>3. After the match Vmeste introduces you and offers to continue the chat<br><br>Work performed in the state LTD. "Internet Agency LEGION (ralegion.ru) an Internal project of the company.',
            'link' => '',
            'img' => 'vmeste',
            'img2' => 'vmeste2'
        ],
        'progressio' => [
            'title' => 'PROGRESSIO',
            'desc' => 'Development of own iOS draft of the Progressio application.<br><br>Progressio — the tool for the accounting of your achievements.<br>Add your purpose, process or a task which progress you want to track.<br>Note complete parts, add new and delete unnecessary. Easily analyze the achievements, work on the maximum results.',
            'link' => '',
            'img' => 'progressio'
        ],
    ],
    '2013' => [
        'bileter' => [
            'title' => 'BILETER',
            'desc' => 'Development of free iOS of the application for service of purchase of tickets.<br>The application allowing to purchase theater tickets on a concert, in a circus. A complete poster of the city, plans of halls, possibility of the choice of places and electronic payment of tickets.<br>Work is performed in a staff of LLC Internet agency LEGION (ralegion.ru)',
            'link' => 'https://itunes.apple.com/app/bileter/id689974792',
            'img' => 'bileter'
        ],
        'cinemates' => [
            'title' => 'CINEMATES',
            'desc' => 'Development of iOS of the application for the Vkino/Cinemates service – vkino.ru (cinemates.com)<br><br>Service for search with whom to go to the cinema<br><br>Work is performed in a staff of LLC Internet agency LEGION (ralegion.ru)',
            'link' => '',
            'img' => 'cinemates',
            'img2' => 'cinemates2'
        ],
        'algeron' => [
            'title' => 'ALGERON',
            'desc' => 'Patient diary<br><br>iOS application for patient diary.<br>Work is performed in a staff of LLC Internet agency LEGION (ralegion.ru)',
            'link' => '',
            'img' => 'algeron',
            'img2' => 'algeron2'
        ],
        'fingerfeel' => [
            'title' => 'FINGER FEEL',
            'desc' => 'Fingerfeel - a condition of the person on a fingerprint.<br><br>The entertaining application for determination of a status of the person on a fingerprint. The application uses the front-facing camera as simulation of the sensor.<br>Apple has rejected from AppStore by reason "Content that could be misleading to users"',
            'link' => '',
            'img' => 'fingerfeel'
        ],
        'kookishcoffee' => [
            'title' => 'KOOKISH COFFEE',
            'desc' => 'Development of free information iOS of the application for Kookish Coffee coffee house',
            'link' => '',
            'img' => 'kookishcoffee'
        ],
    ],
];