<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="keywords" content="Software developer iOS, Software, programming, iOS Software development, Mobile applications development, freelancer, engineer, iOS, Apple">
    <meta name="theme-color" content="#7ec9ab">
    <link rel="stylesheet" href="../css/style.css">
    <title>Roman Resenchuk | Software development engineer, manager (iOS applications)</title>
</head>
<body>

<header>
    <div class="container">
        <div class="logo">
            <a href="/">
                <h1>Roman Resenchuk<small>Software Development Engineer</small></h1>
            </a>
        </div>
        <div class="menu">
            <ul>
                <li><a href="../projects" >All works</a></li>
                <li><a href="../#aboutme" class="scrollto">About me</a></li>
                <li><a href="../#contactme" class="scrollto">Contact me</a></li>
            </ul>
        </div>
    </div>
</header>